# Generated by Django 2.2.7 on 2019-11-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('appleId', models.AutoField(db_column='appleId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('manittoId', models.ForeignKey(blank=True, db_column='manittoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='manitto.Apple')),
            ],
        ),
    ]
