# Generated by Django 2.2.7 on 2019-11-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manitto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='manittoId',
            field=models.ForeignKey(blank=True, db_column='manittoId', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manitto.Apple'),
        ),
    ]
