# Generated by Django 2.2.7 on 2019-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manitto', '0002_auto_20191105_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apple',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
